version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: tasklinkadmin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TaskLink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: postgres-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pg

networks:
  pg:
    name: pg
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: